spring:
  config:
    activate:
      on-profile: go

  datasource:
    url: jdbc:mysql://localhost:3306/medi?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

    ### SQL INIT for Batch ###
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-batch.sql
  ### BATCH ###
  batch:
    jdbc:
      initialize-schema: always
    platform: mysql