spring:
  ### CONFIG ###
  config:
    activate:
      on-profile: han
  ### DATABASE ###
  datasource:
    url: jdbc:mysql://localhost:3306/medi?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: springproject
    driver-class-name: com.mysql.cj.jdbc.Driver
  ### JPA ###
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
  ### SQL INIT for Batch ###
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-batch.sql
  ### BATCH ###
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: true
    platform: mysql
  ### redis ###
  data:
    redis:
      host: localhost
      port: 6379
