spring:
  config:
    activate:
      on-profile: hyun

  datasource:
    url: jdbc:mysql://localhost:3308/medi?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
